Repository UBC-MDS/rpuck, pull requests merged in 2020-02, with the labels that each got.

#8 project setup and add season attendance function
  .DS_Store
  .Rbuildignore
  .gitignore
  CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  DESCRIPTION
  LICENSE
  LICENSE.md
  NAMESPACE
  R/.DS_Store
  R/attendance.R
  R/player_stats.R
  README.Rmd
  README.html
  README.md
  img/pypuck_logo.png
  img/rpuck_logo.png
  man/attendance.Rd
  man/figures/README-pressure-1.png
  man/player_stats.Rd
  rpuck.Rproj
  tests/testthat.R
  tests/testthat/test-attendance.R
  tests/testthat/test-player_stats.R
Labels: documentation, group, individual

#9 added the player stats function definition
  R/attendance.R
  R/player_stats.R
Labels: enhancement, individual

#11 Added function docstring and ReadMe
  R/draft_pick.R
  README.Rmd
  README.md
Labels: documentation
