Repository UBC-MDS/rpuck, pull requests merged in 2020-03, with the labels that each got.

#18 Draft pick function update
  R/draft_pick.R
  README.Rmd
  README.md
Labels: enhancement

#20 Draft pick
  R/draft_pick.R
  tests/testthat.R
  tests/testthat/test-draft_pick.R
Labels: enhancement, individual

#22 Attendance function and tests added
  .DS_Store
  DESCRIPTION
  NAMESPACE
  R/attendance.R
  README.Rmd
  README.md
  man/attendance.Rd
  man/draft_pick.Rd
  man/player_stats.Rd
  tests/testthat/test-attendance.R
  tests/testthat/test-player_stats.R
Labels: enhancement, individual

#24 modify based on check()
  DESCRIPTION
  NAMESPACE
  R/attendance.R
  R/draft_pick.R
  man/attendance.Rd
  man/draft_pick.Rd
  man/player_stats.Rd
  man/team_stats.Rd
  tests/testthat/test-draft_pick.R
  tests/testthat/test-player_stats.R
Labels: bug, documentation, enhancement

#28 add test function call
  R/draft_pick.R
  tests/testthat/test-draft_pick.R
  tests/testthat/test-player_stats.R
  tests/testthat/test-team_stats.R
Labels: bug

#30 build website for rpuck via pkgdown
  docs/404.html
  docs/CONDUCT.html
  docs/CONTRIBUTING.html
  docs/CONTRIBUTORS.html
  docs/LICENSE-text.html
  docs/LICENSE.html
  docs/authors.html
  docs/docsearch.css
  docs/docsearch.js
  docs/index.html
  docs/link.svg
  docs/pkgdown.css
  docs/pkgdown.js
  docs/pkgdown.yml
  docs/reference/attendance-1.png
  docs/reference/attendance.html
  docs/reference/draft_pick.html
  docs/reference/figures/README-pressure-1.png
  docs/reference/index.html
  docs/reference/player_stats.html
  docs/reference/team_stats.html
Labels: documentation, enhancement

#31 added missing parameter documentation for player_stats arguments to t…
  R/player_stats.R
Labels: bug, documentation

#32 Build and Add covdcov, etc
  .Rbuildignore
  .github/.gitignore
  .github/workflows/R-CMD-check.yaml
  .github/workflows/check-release.yaml
  DESCRIPTION
  README.Rmd
  README.md
Labels: enhancement, group

#33 Changes to draft function and tests
  R/draft_pick.R
  tests/testthat/test-draft_pick.R
Labels: bug

#34 modify docstring
  DESCRIPTION
  NAMESPACE
  R/team_stats.R
  man/player_stats.Rd
  man/team_stats.Rd
  tests/testthat/test-draft_pick.R
Labels: bug

#35 Draft pick
  R/draft_pick.R
Labels: enhancement

#36 add coverage report
  R/attendance.R
Labels: enhancement

#40 modify readme
  README.Rmd
  README.md
Labels: documentation

#42 rebuild
  .github/workflows/R-CMD-check.yaml
  .github/workflows/check-release.yaml
Labels: bug

#45 added more tests to player_stats function to get the coverage up
  tests/testthat/test-player_stats.R
Labels: enhancement

#49 added dependencies to table in readme closing #48
  README.Rmd
  README.md
Labels: documentation

#52 Draft pick
  DESCRIPTION
  README.Rmd
  tests/testthat/test-attendance.R
Labels: documentation
